[package]
name = "research"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
domain = { path = "../domain" }
log = "0.4.22"
rayon = "1.10.0"
egui = {version = "0.29.1", features = ["color-hex"]}