[package]
name = "perlin"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.2"
glam = "0.29.0"
glium = "0.36.0"
image = "0.25.4"
eframe = "0.29.1"
rayon = "1.10.0"
domain = { path = "../domain" }
svg = "0.18.0"